### ISSUE TITLE
How does this unit test work?

### ISSUE THREAD

**Issue by dk2k** [julianthome/autorex#1]
https://github.com/julianthome/autorex/blob/ddc713a08d465ed3c9830e85103bafb4e45189cb/src/test/java/org/snt/autorex/TestClassification.java#L49
Don't seem to use any Assert.

**Comment by julianthome** [comment]
Thanks a lot @dk2k 👍  Yes, indeed,  this test case does not do anything. I created a PR to eliminate this unit test and the corresponding class.
